import os 
from dotenv import load_dotenv 

from build_pdfs import PDFBuilder 
from chatgpt import ChatGPT

# loading environment variables
load_dotenv('.env') 
API_KEY = '' # OpenAI API KEY


def main():
    """Create a PDF file with the answers generated by the 
    ChatGPT for the questions."""
    title = input('Enter the title of the subject: ').strip()
    filePath = input('Enter the questions file path: ')
     
    with open(filePath) as file:
        questions = file.read().split('\n') 
        
    pdfBuilder = PDFBuilder(title)  # PDFBuilder instance
    chatgpt = ChatGPT(API_KEY)      # ChatGPT instance
    
    for question in questions: 
        pdfBuilder.addQuestion(question)
        prompt = f'In {title}, {question}'
        answer = chatgpt.response(prompt)
        pdfBuilder.addAnswer(answer.split('\n'))
        
    pdfBuilder.build()    # creating the pdf
    
    
if __name__ == '__main__': 
    try:
        main()
    except Exception as e:
        print(e)
